title: "[General] "
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Welcome! Please use this template to ask any question you have about the project, setup, usage, or related topics.
  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: "Provide a clear and concise description of your question."
      placeholder: "Describe your question here"
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context or relevant details that might help me understand your question better."
      placeholder: "Optional: Add context or additional info"