"""add weather travel_info and version tables

Revision ID: 8f606966675c
Revises: fd393ab4c012
Create Date: 2026-03-22 16:55:44.576521

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8f606966675c'
down_revision = 'fd393ab4c012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_travel_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('visa_required', sa.Boolean(), nullable=True),
    sa.Column('visa_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vaccinations', sa.JSON(), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=True),
    sa.Column('insurance_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embassy_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embassy_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embassy_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('local_emergency_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('insurance_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('insurance_policy_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('insurance_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('general_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_trip_travel_info_trip_id_trip'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_travel_info'))
    )
    with op.batch_alter_table('trip_travel_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_travel_info_trip_id'), ['trip_id'], unique=True)

    op.create_table('trip_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_trip_version_trip_id_trip'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_version'))
    )
    with op.batch_alter_table('trip_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_version_trip_id'), ['trip_id'], unique=False)

    op.create_table('day_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('high_temp', sa.Float(), nullable=True),
    sa.Column('low_temp', sa.Float(), nullable=True),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rain_chance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['tripday.id'], name=op.f('fk_day_weather_day_id_tripday'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_day_weather'))
    )
    with op.batch_alter_table('day_weather', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_weather_day_id'), ['day_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_weather', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_weather_day_id'))

    op.drop_table('day_weather')
    with op.batch_alter_table('trip_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_version_trip_id'))

    op.drop_table('trip_version')
    with op.batch_alter_table('trip_travel_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_travel_info_trip_id'))

    op.drop_table('trip_travel_info')
    # ### end Alembic commands ###

