"""add place_details and tripitem_details tables

Revision ID: da76d4a0eaec
Revises: bfbce549e783
Create Date: 2026-03-22 15:03:47.403778

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'da76d4a0eaec'
down_revision = 'bfbce549e783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('tips', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_place_details_place_id_place'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_details'))
    )
    with op.batch_alter_table('place_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_place_details_place_id'), ['place_id'], unique=True)

    op.create_table('tripitem_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('confirmation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('alternative_item_id', sa.Integer(), nullable=True),
    sa.Column('alternative_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['alternative_item_id'], ['tripitem.id'], name=op.f('fk_tripitem_details_alternative_item_id_tripitem'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['tripitem.id'], name=op.f('fk_tripitem_details_item_id_tripitem'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tripitem_details'))
    )
    with op.batch_alter_table('tripitem_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tripitem_details_item_id'), ['item_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tripitem_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tripitem_details_item_id'))

    op.drop_table('tripitem_details')
    with op.batch_alter_table('place_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_place_details_place_id'))

    op.drop_table('place_details')
    # ### end Alembic commands ###

