"""User settings modes: Low Network, Dark, GPX bubble

Revision ID: dd7a55d2ae42
Revises: 7c0ec2b61abb
Create Date: 2025-08-03 08:24:09.825100

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "dd7a55d2ae42"
down_revision = "7c0ec2b61abb"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE user ADD COLUMN mode_low_network BOOLEAN NOT NULL DEFAULT 1;")
    op.execute("ALTER TABLE user ADD COLUMN mode_dark BOOLEAN NOT NULL DEFAULT 0;")
    op.execute("ALTER TABLE user ADD COLUMN mode_gpx_in_place BOOLEAN NOT NULL DEFAULT 0;")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("mode_gpx_in_place")
        batch_op.drop_column("mode_dark")
        batch_op.drop_column("mode_low_network")

    # ### end Alembic commands ###
