"""add phase 2 tables restaurants routes reservations budget

Revision ID: fd393ab4c012
Revises: da76d4a0eaec
Create Date: 2026-03-22 15:53:14.829636

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fd393ab4c012'
down_revision = 'da76d4a0eaec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('fetched_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_rate'))
    )
    op.create_table('trip_accommodation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('check_in', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('check_out', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost_per_night', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_trip_accommodation_trip_id_trip'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_accommodation'))
    )
    with op.batch_alter_table('trip_accommodation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_accommodation_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('planned_amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_trip_budget_trip_id_trip'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_budget'))
    )
    with op.batch_alter_table('trip_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_budget_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('airline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flight_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('departure_airport', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('departure_datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arrival_airport', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arrival_datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seat_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_trip_flight_trip_id_trip'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_flight'))
    )
    with op.batch_alter_table('trip_flight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_flight_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_rental_car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pickup_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pickup_datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dropoff_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dropoff_datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost_per_day', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_trip_rental_car_trip_id_trip'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_rental_car'))
    )
    with op.batch_alter_table('trip_rental_car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_rental_car_trip_id'), ['trip_id'], unique=False)

    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_dish_place_id_place'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dish'))
    )
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dish_place_id'), ['place_id'], unique=False)

    op.create_table('restaurant_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('cuisine', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reservation_required', sa.Boolean(), nullable=True),
    sa.Column('must_try', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_restaurant_details_place_id_place'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurant_details'))
    )
    with op.batch_alter_table('restaurant_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_details_place_id'), ['place_id'], unique=True)

    op.create_table('item_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_item_id', sa.Integer(), nullable=False),
    sa.Column('to_item_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('recommended_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['tripday.id'], name=op.f('fk_item_route_day_id_tripday'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_item_id'], ['tripitem.id'], name=op.f('fk_item_route_from_item_id_tripitem'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_item_id'], ['tripitem.id'], name=op.f('fk_item_route_to_item_id_tripitem'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_route'))
    )
    with op.batch_alter_table('item_route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_route_day_id'), ['day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_route_from_item_id'), ['from_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_route_to_item_id'), ['to_item_id'], unique=False)

    op.create_table('route_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('line_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['item_route.id'], name=op.f('fk_route_option_route_id_item_route'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_option'))
    )
    with op.batch_alter_table('route_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_option_route_id'), ['route_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_option_route_id'))

    op.drop_table('route_option')
    with op.batch_alter_table('item_route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_route_to_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_route_from_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_route_day_id'))

    op.drop_table('item_route')
    with op.batch_alter_table('restaurant_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_details_place_id'))

    op.drop_table('restaurant_details')
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_place_id'))

    op.drop_table('dish')
    with op.batch_alter_table('trip_rental_car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_rental_car_trip_id'))

    op.drop_table('trip_rental_car')
    with op.batch_alter_table('trip_flight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_flight_trip_id'))

    op.drop_table('trip_flight')
    with op.batch_alter_table('trip_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_budget_trip_id'))

    op.drop_table('trip_budget')
    with op.batch_alter_table('trip_accommodation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_accommodation_trip_id'))

    op.drop_table('trip_accommodation')
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###

