name: Bug Report
about: Report something that is not working as expected.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - itskovacs

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug you encountered"
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: "To Reproduce"
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: "List the steps to reproduce the bug"
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Describe the expected behavior"
      required: false

  - type: input
    id: trip_version
    attributes:
      label: "TRIP Version"
      description: "Specify the version of the TRIP application you are using (if applicable)."
      placeholder: "e.g., 1.19.1"
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots (if applicable)"
      description: "Add screenshots to help explain your problem."
      placeholder: "Paste image URLs or describe screenshots"
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: "Browser"
      options:
        - "Chrome"
        - "Firefox"
        - "Edge"
        - "Safari"
        - "Opera"
        - "Other"

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
      placeholder: "Additional information"
      required: false