blank_issues_enabled: false
contact_links:
  - name: Feature Request and Ideas
    url: https://github.com/itskovacs/trip/discussions/categories/ideas
    about: Have a feature request or specific need? Join the conversation about how it could enhance the project
  - name: Question or Problem
    url: https://github.com/itskovacs/trip/discussions/categories/general
    about: Whether it's about setup, configuration, or general usage, feel free to ask.